name = "daikonsv-worker"
main = "index.ts"
compatibility_date = "2026-06-07"

account_id = "5db62c40fa12568a80a8667cd5713801"
[[d1_databases]]
binding = "RSS"
database_name = "rss-db"
database_id = "2adb3be5-99e5-4071-b619-b5c16cf06a27"